import AppKit
import CoreGraphics
import Foundation

enum DisplayBackgroundWorkPolicy {
    static func shouldApplyAutomation(
        displayAutomationAllowed: Bool,
        hasDesiredClose: Bool,
        hasPendingReconnect: Bool
    ) -> Bool {
        // A close switch is an explicit, persisted display intent. Reapplying
        // it after launch or hot-plug does not depend on the separate optional
        // background-automation consent. Legacy timed reconnect work keeps its
        // existing consent requirement.
        hasDesiredClose || (displayAutomationAllowed && hasPendingReconnect)
    }

    static func shouldMonitor(
        displayAutomationAllowed: Bool,
        hasDesiredClose: Bool,
        hasPendingReconnect: Bool,
        hasAppDisconnectedDisplays: Bool
    ) -> Bool {
        hasAppDisconnectedDisplays || shouldApplyAutomation(
            displayAutomationAllowed: displayAutomationAllowed,
            hasDesiredClose: hasDesiredClose,
            hasPendingReconnect: hasPendingReconnect
        )
    }
}

enum DisplayReconfigurationPolicy {
    static func shouldHandle(
        flags: CGDisplayChangeSummaryFlags,
        shouldSuppressRecentMutation: Bool
    ) -> Bool {
        let isTopologyChange = flags.contains(.addFlag) || flags.contains(.removeFlag)
        let isDisplayStateChange = flags.contains(.setModeFlag)
            || flags.contains(.enabledFlag)
            || flags.contains(.disabledFlag)
        guard isTopologyChange || isDisplayStateChange else {
            return false
        }

        // A real display may be connected or removed immediately after this app
        // changes another display. Topology changes must never be discarded as a
        // side effect of suppressing callbacks generated by our own mutation.
        return isTopologyChange || !shouldSuppressRecentMutation
    }

    static func requiresSettledSafetyCheck(flags: CGDisplayChangeSummaryFlags) -> Bool {
        flags.contains(.removeFlag)
    }
}

final class AutomationController {
    private let store: ProfileStore
    private let disconnect: SoftDisconnectController
    private let logger: AppLogger
    private let queue = DispatchQueue(label: "com.fusheng.mac-tool.display-automation", qos: .userInitiated)
    private var pendingDisplayChangeWorkItem: DispatchWorkItem?
    private var pendingSettledSafetyWorkItem: DispatchWorkItem?
    private var isMonitoringDisplayChanges = false

    var onChange: (() -> Void)?

    init(
        store: ProfileStore,
        disconnect: SoftDisconnectController,
        logger: AppLogger = .shared
    ) {
        self.store = store
        self.disconnect = disconnect
        self.logger = logger
    }

    func start() {
        updateBackgroundActivity(performInitialCheck: false)
        applyAll(reason: "app-start")
    }

    func updateBackgroundActivity() {
        updateBackgroundActivity(performInitialCheck: true)
    }

    private func updateBackgroundActivity(performInitialCheck: Bool) {
        let shouldMonitor = hasBackgroundDisplayWork()
        if shouldMonitor && !isMonitoringDisplayChanges {
            startMonitoringDisplayChanges()
            if performInitialCheck {
                // A topology callback may already have happened before safety
                // ownership was persisted and monitoring became active.
                applySafetyRecovery(reason: "monitor-start")
            }
        } else if !shouldMonitor && isMonitoringDisplayChanges {
            stopMonitoringDisplayChanges()
        }
    }

    func stop() {
        stopMonitoringDisplayChanges()
    }

    private func startMonitoringDisplayChanges() {
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(handleWake),
            name: NSWorkspace.didWakeNotification,
            object: NSWorkspace.shared
        )
        CGDisplayRegisterReconfigurationCallback(displayReconfigurationCallback, UnsafeMutableRawPointer(Unmanaged.passUnretained(self).toOpaque()))
        isMonitoringDisplayChanges = true
    }

    private func stopMonitoringDisplayChanges() {
        queue.async { [weak self] in
            self?.pendingDisplayChangeWorkItem?.cancel()
            self?.pendingDisplayChangeWorkItem = nil
            self?.pendingSettledSafetyWorkItem?.cancel()
            self?.pendingSettledSafetyWorkItem = nil
        }
        guard isMonitoringDisplayChanges else {
            return
        }
        CGDisplayRemoveReconfigurationCallback(displayReconfigurationCallback, UnsafeMutableRawPointer(Unmanaged.passUnretained(self).toOpaque()))
        NotificationCenter.default.removeObserver(self)
        isMonitoringDisplayChanges = false
    }

    func applyAll(reason: String) {
        guard hasBackgroundDisplayWork() else {
            return
        }
        let localized = localizedReason(reason)
        queue.async { [weak self] in
            guard let self else { return }
            guard self.hasBackgroundDisplayWork() else { return }
            if self.shouldApplyConfiguredDisplayIntent() {
                self.disconnect.applyDesiredDisplayStates(store: self.store, reason: localized)
            } else if self.hasSafetyRecoveryWork() {
                // Restoring a display closed by this app is a safety guarantee of
                // the user's explicit action, not background display automation.
                self.disconnect.enforceDisplaySafety(store: self.store, reason: localized)
            }
            self.logger.info("显示器状态检查完成，触发来源：\(localized)")
            self.onChange?()
        }
    }

    private func applySafetyRecovery(reason: String) {
        guard hasSafetyRecoveryWork() else {
            return
        }
        let localized = localizedReason(reason)
        queue.async { [weak self] in
            guard let self, self.hasSafetyRecoveryWork() else { return }
            self.disconnect.enforceDisplaySafety(store: self.store, reason: localized)
            self.logger.info("显示器安全检查完成，触发来源：\(localized)")
            self.onChange?()
        }
    }

    @objc private func handleWake() {
        applyAll(reason: "wake")
    }

    fileprivate func handleDisplayReconfiguration(display: CGDirectDisplayID, flags: CGDisplayChangeSummaryFlags) {
        guard hasBackgroundDisplayWork() else {
            return
        }
        let shouldSuppress = disconnect.shouldSuppressDisplayEvent()
        guard DisplayReconfigurationPolicy.shouldHandle(
            flags: flags,
            shouldSuppressRecentMutation: shouldSuppress
        ) else {
            if shouldSuppress {
                logger.info("忽略本应用显示器操作触发的系统回调。")
            }
            return
        }
        queue.async { [weak self] in
            self?.debounceDisplayChange(
                requiresSettledSafetyCheck: DisplayReconfigurationPolicy.requiresSettledSafetyCheck(flags: flags)
            )
        }
    }

    private func debounceDisplayChange(requiresSettledSafetyCheck: Bool) {
        guard hasBackgroundDisplayWork() else {
            return
        }
        pendingDisplayChangeWorkItem?.cancel()
        let workItem = DispatchWorkItem { [weak self] in
            self?.applyAll(reason: "display-change")
        }
        pendingDisplayChangeWorkItem = workItem
        queue.asyncAfter(deadline: .now() + 0.6, execute: workItem)

        if requiresSettledSafetyCheck {
            pendingSettledSafetyWorkItem?.cancel()
            let settledWorkItem = DispatchWorkItem { [weak self] in
                self?.applySafetyRecovery(reason: "display-remove-settled")
            }
            pendingSettledSafetyWorkItem = settledWorkItem
            queue.asyncAfter(deadline: .now() + 2.5, execute: settledWorkItem)
        }
    }

    private func hasBackgroundDisplayWork() -> Bool {
        DisplayBackgroundWorkPolicy.shouldMonitor(
            displayAutomationAllowed: store.displayAutomationAllowed,
            hasDesiredClose: hasDesiredClose,
            hasPendingReconnect: !store.pendingReconnects.isEmpty,
            hasAppDisconnectedDisplays: hasSafetyRecoveryWork()
        )
    }

    private var hasDesiredClose: Bool {
        store.profiles.contains { disconnect.desiredCloseEnabled(profile: $0) }
    }

    private func shouldApplyConfiguredDisplayIntent() -> Bool {
        DisplayBackgroundWorkPolicy.shouldApplyAutomation(
            displayAutomationAllowed: store.displayAutomationAllowed,
            hasDesiredClose: hasDesiredClose,
            hasPendingReconnect: !store.pendingReconnects.isEmpty
        )
    }

    private func hasSafetyRecoveryWork() -> Bool {
        !store.state.appDisconnectedDisplayIDs.isEmpty
    }

    private func localizedReason(_ reason: String) -> String {
        switch reason {
        case "app-start":
            return "应用启动"
        case "wake":
            return "系统唤醒"
        case "display-change":
            return "显示器变化"
        case "monitor-start":
            return "安全监听启动"
        case "display-remove-settled":
            return "显示器移除后复查"
        case "manual":
            return "手动操作"
        case "manual-all":
            return "手动全部应用"
        case "reconnect":
            return "重新连接"
        case "pending-already-connected":
            return "启动恢复"
        default:
            return reason
        }
    }
}

private func displayReconfigurationCallback(
    display: CGDirectDisplayID,
    flags: CGDisplayChangeSummaryFlags,
    userInfo: UnsafeMutableRawPointer?
) {
    guard let userInfo else {
        return
    }
    let controller = Unmanaged<AutomationController>.fromOpaque(userInfo).takeUnretainedValue()
    controller.handleDisplayReconfiguration(display: display, flags: flags)
}
