import Foundation

public enum DisplaySafetyPolicy {
    public static let maximumAttempts = 3
    public static let circuitBreakerDuration: TimeInterval = 5 * 60
    public static let selfEventSuppressionDuration: TimeInterval = 2

    public static func isAutomationEligible(
        profileEnabled: Bool,
        disconnectEnabled: Bool,
        allowSoftDisconnect: Bool
    ) -> Bool {
        profileEnabled && disconnectEnabled && allowSoftDisconnect
    }

    public static func retryDelay(afterAttempt attempt: Int) -> TimeInterval {
        0.2 * pow(2, Double(max(0, attempt - 1)))
    }

    public static func circuitOpenUntil(failureDate: Date) -> Date {
        failureDate.addingTimeInterval(circuitBreakerDuration)
    }

    public static func shouldSuppressEvent(lastMutation: Date?, now: Date) -> Bool {
        guard let lastMutation else { return false }
        return now.timeIntervalSince(lastMutation) < selfEventSuppressionDuration
    }
}

public enum ClipboardPrivacyPolicy {
    public static let defaultRetentionDays = 30
    public static let migrationBatchSize = 50
    public static let sensitiveMarkers: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.1password.declaretypes"
    ]

    public static func containsSensitiveMarker(_ rawTypes: [String]) -> Bool {
        !sensitiveMarkers.isDisjoint(with: Set(rawTypes))
    }

    public static func batchRanges(itemCount: Int) -> [Range<Int>] {
        guard itemCount > 0 else { return [] }
        return stride(from: 0, to: itemCount, by: migrationBatchSize).map {
            $0..<min($0 + migrationBatchSize, itemCount)
        }
    }
}

public enum ConfigurationRecoveryPolicy {
    public static let directoryPermissions = 0o700
    public static let filePermissions = 0o600

    public static func requiresMigration(schemaVersion: Int, currentVersion: Int) -> Bool {
        schemaVersion < currentVersion
    }

    public static func canImport(schemaVersion: Int, currentVersion: Int) -> Bool {
        schemaVersion <= currentVersion
    }
}
